### PR TITLE
Fix for RH8

### PR DESCRIPTION
**Pull request by cdeepali**
## Checklist before submitting

- [x] Did you read the [contributor guide](https://github.com/open-ce/open-ce/blob/master/CONTRIBUTING.md)?
- [ ] Did you update any affected [documentation](https://github.com/open-ce/open-ce/blob/master/doc/)?
- [ ] Did you write any [tests](https://github.com/open-ce/open-ce/blob/master/tests/) to validate this change?  

## Description

Fixes https://github.com/open-ce/numactl-feedstock/issues/7.

## Review process to land 

1. All tests and other checks must succeed.
2. At least one [maintainer](https://github.com/open-ce/open-ce/blob/master/MAINTAINERS.md) must review and approve.
3. If any  [maintainer](https://github.com/open-ce/open-ce/blob/master/MAINTAINERS.md) requests changes, they must be addressed.

### CODE REVIEW

**Comment by bnemanich** [comment]
Why was this test failing? It seems like we were previously trying to verify that the conda version of numactl was being used, and now we aren't testing for that.

**Comment by jayfurmanek** [comment]
I like the new test - its more of a test of function vs just an install test. I dont think we necessarily need to have the `grep conda` there.

**Comment by bnemanich** [comment]
I think it would make sense to have both if possible. Otherwise we might just be testing that the system's version of numactl works properly.

**Comment by cdeepali** [comment]
yeah for some reason the test 'which numactl' is not passing. Although `numactl` works fine. 
Manually executing `which numactl` after adding test env path to PATH causes a segfault.

**Comment by bnemanich** [comment]
Is this PR still required?

**Comment by cdeepali** [comment]
Closing it.

**Pull request closed without merging**
